Springfield/Springfield/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""Springfield URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("candidates.urls")),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Springfield/candidates/urls.py
from django.urls import path

from . import views

app_name = 'candidates'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:candidate_id>/vote/', views.vote, name='vote'),
]

Springfield/candidates/models.py
from django.contrib.gis.db import models


class Candidate(models.Model):
    name = models.CharField(max_length=50)
    photo = models.ImageField()
    text = models.TextField()
    location = models.PointField()
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

Springfield/candidates/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Candidate
from django.http import HttpResponseRedirect



class IndexView(generic.ListView):
    model = Candidate
    template_name = 'candidates/index.html'
    context_object_name = 'candidates'


class DetailView(generic.DetailView):
    model = Candidate
    template_name = 'candidates/detail.html'


def vote(request, candidate_id):
    candidate = get_object_or_404(Candidate, pk=candidate_id)
    candidate.votes += 1
    candidate.save()
    return HttpResponseRedirect(reverse('candidates:detail', args=(candidate.id,)))

Springfield/candidates/templates/candidates/detail.html
{% extends "candidates/layout.html" %}

{% block content %}
<div class="profile">
    <img src="{{ candidate.photo.url }}">
    <h1>{{ candidate.name }}</h1>
    <div>Počet hlasů: {{ candidate.votes }}</div>
    <form action="{% url 'candidates:vote' candidate.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Vote">
    </form>
</div>
<div class="bydliste">Bydliště</div>
<div id="map"></div>
<p class="text">{{ candidate.text }}</p>
{% endblock content %}

{% block assets %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
   integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
   crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
   integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
   crossorigin=""></script>

<style>
    #map {
        height: 250px;
        width: 100%;
    }

    .profile {
        text-align: center;
        margin-bottom: 24px;
    }

    .profile h1 {
        font-size: 65px;

    }

    .profile img {
        width: 400px;
    }

    .text {
        text-align: center;
        font-size: 20px;
        line-height: 1.5;
        margin-top: 30px;
    }
    .bydliste {
        font-size: 20px;
        margin-bottom: 15px;
        margin-top: 40px;
        text-align: center;
    }
</style>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var map = L.map('map').setView([{{ candidate.location.y }}, {{ candidate.location.x }}], 11);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);
        var marker = L.marker([{{ candidate.location.y }}, {{ candidate.location.x }}]).addTo(map);
    });
</script>
{% endblock assets %}

Springfield/candidates/templates/candidates/index.html
{% extends "candidates/layout.html" %}

{% block content %}
<h1>Vítejte ve Springfieldu!</h1>
<h2>Kdo bude náš nový starosta?</h2>

{% if candidates %}
    <ul class="candidate">
    {% for candidate in candidates %}
        <li><a href="{% url 'candidates:detail' candidate.id %}">{{ candidate.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No candidates are available.</p>
{% endif %}
{% endblock content %}

{% block assets %}
<style>
    body {
        background-color: yellow;
        text-align: center;
        margin-top: 220px;
    }
    h1 {
        font-size: 70px;
        margin-bottom: 50px;
    }
    h2 {
        font-size: 30px;
    }
    .candidate {
        font-size: 20px;
        padding-left: 0;
    }
    .candidate li {
        list-style: none;
        margin-bottom: 10px;
    }
    .candidate a {
        color: black;
        line-height: 1.5;
    }
</style>
{% endblock assets %}

Springfield/candidates/templates/candidates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        footer {
            margin-top: 80px;
            text-align: center;
            color: gray;
        }
    </style>
    {% block assets %}{% endblock assets %}
</head>
<body>
    {% block content %}{% endblock content %}
    <footer>
        Autoři stránky: Rostislav Hořava, Žaneta Rezková, Jakub Řehák
    </footer>
</body>
</html>